# Generated by Django 5.1.6 on 2025-02-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenapp', '0003_fooditems_description_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='canteen_images/'),
        ),
    ]
